#!/usr/bin/env bash

if psql postgres --command "SELECT 1 FROM pg_database WHERE datname = 'conduit';" | grep -q 1; then
  dropdb conduit
  echo "Database dropped."
else
  echo "Database doesn't exist."
fi
