#!/usr/bin/env bash

set -e

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  echo "Usage: update-dep owner repo rev"
  exit 1
fi

echo "Ensure nix/$2 exists"
mkdir -p "nix/$2"

echo "Writing rev ($3) to nix/$2/rev"
echo $3 > nix/$2/rev

echo "Fetching and writing sha to nix/$2/sha"
set -x
nix-prefetch-url \
  https://github.com/$1/$2/archive/$3.tar.gz \
  --unpack \
  > nix/$2/sha
