#!/usr/bin/env bash

set -e

echo "Writing rev ($1) to nix/nipkgs-rev.txt"
echo $1 > nix/nixpkgs-rev.txt

echo "Fetching and writing sha to nix/nipkgs-sha.txt"
set -x
nix-prefetch-url \
  https://github.com/NixOS/nixpkgs/archive/$1.tar.gz \
  --unpack \
  > nix/nixpkgs-sha.txt
