#!/usr/bin/env bash

expression=$(cat <<-NIX
with import ./nix/packages/nixpkgs {};
stdenv.mkDerivation {
  name = "temp-hpack-cabal2nix";
  buildInputs = [
    haskellPackages.hpack
    haskellPackages.cabal2nix
  ];
}
NIX
)

nix-shell \
  --expr "$expression" \
  --run 'hpack && cabal2nix . > package.nix'
